### ISSUE TITLE
How to kill a running command in sbt shell?

### ISSUE THREAD

**Issue by chtlp** [ensime/emacs-sbt-mode#13]
Hi, I wanted to kill a long running sbt run in the sbt shell, but found that neither Ctrl-D or Ctrl-C Ctril-C worked. How to kill the program? (instead of just killing the whole buffer)

**Comment by hvesalai** [comment]
See also #28

**Comment by fommil** [comment]
I thought this was a shortcoming of `sbt` itself... you can enable cancelling of commands by enabling `cancelable in Global := true` like we recommend in https://github.com/ensime/ensime-sbt

**Comment by fommil** [comment]
this is weird I used to be able to use `C-c l` but now it is unbound. What function was this calling?

**Comment by jvliwanag** [comment]
`sbt-clear`

**Comment by fommil** [comment]
ah! that was the last commit. thanks.

**Comment by fommil** [comment]
this was fixed a while ago: make sure to set `cancelable in Global := true` and then recall that in order to send a control sequence to the sbt-mode subprocess, first run `sbt-clear` (bound to C-c C-v by default) then `C-c` to get into "send escape sequence". e.g. to send `C-c` to sbt, type `C-c C-v C-c C-c`

**Comment by hoff2** [comment]
@fommil did you fix it? Thanks for either fixing it or telling us about it, whichever you do.

**Comment by peterbecich** [comment]
`C-c C-v C-c C-d` worked for me.
